- alias: Patio - Motion On
  trigger:
    platform: state
    entity_id: binary_sensor.patio_motion
    to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: switch.turn_on
      entity_id: switch.patio
    - service: timer.start
      entity_id: timer.patio_lights_off

- alias: Patio - Off after 10
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.patio_lights_off
  action:
    - service: switch.turn_off
      entity_id: switch.patio

- alias: Patio - Door sensor on
  trigger:
    platform: state
    entity_id: binary_sensor.backdoor_sensor
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: switch.turn_on
      entity_id: switch.patio
    - service: timer.start
      entity_id: timer.patio_lights_off

- alias: Pico - On
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.main_pico
    to: '1'
  action:
    service: scene.turn_on
    entity_id: scene.daytime

- alias: Pico - Off
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.main_pico
    to: '4'
  action:
    service: scene.turn_on
    entity_id: scene.night_light

- alias: Pico - Up
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.main_pico
    to: '8'
  action:
    service: scene.turn_on
    entity_id: scene.evening

- alias: Pico - Down
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.main_pico
    to: '16'
  action:
    service: scene.turn_on
    entity_id: scene.mains_low

- alias: Pico - Button
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.main_pico
    to: '2'
  action:
    service: light.turn_off
    entity_id: group.all_lights

- alias: Master Pico - Off
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.master_bedroom_pico
    to: '4'
  action:
    service: switch.turn_off
    entity_id: switch.white_noise

- alias: Master Pico - On
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.master_bedroom_pico
    to: '1'
  action:
    service: switch.turn_on
    entity_id: switch.white_noise

- alias: Lights on before sunset
  trigger:
    platform: sun
    event: sunset
    offset: '-02:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.daytime

- alias: Front porch lights on at sunset
  hide_entity: True
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    entity_id: light.front_porch_overhead_light

- alias: Front porch lights off at sunrise
  hide_entity: True
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id: light.front_porch_overhead_light

- alias: Halloween lights on at 5
  hide_entity: False
  trigger:
    platform: time
    at: '17:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.kitchen_halloween
    - service: switch.turn_on
      entity_id: switch.living_room_halloween

- alias: Halloween lights off at 9
  hide_entity: False
  trigger:
    platform: time
    at: '9:00:00'
  action:
    - service: switch.turn_off
      entity_id: switch.kitchen_halloween
    - service: switch.turn_off
      entity_id: switch.living_room_halloween

- alias: Evening lighting at 7:50
  initial_state: True
  trigger:
    platform: time
    at: '19:50:00'
  action:
    service: scene.turn_on
    entity_id: scene.evening

- alias: Evening lighting at 8:30
  initial_state: False
  trigger:
    platform: time
    at: '20:30:00'
  action:
    service: scene.turn_on
    entity_id: scene.evening

- alias: Ignore motion after mains off
  hide_entity: True
  trigger:
    platform: state
    entity_id: light.main_lights
    to: 'off'
  action:
    service: timer.start
    entity_id: timer.livingroom_motion_ignore

- alias: Mains on night Motion
  trigger:
    platform: state
    entity_id: binary_sensor.livingroom
    to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: time
          after: '21:30:00'
        - condition: sun
          before: sunrise
          before_offset: '01:00:00'
    - condition: state
      entity_id: counter.livingroom_motion_ignore
      state: 'idle'
  action:
    service: scene.turn_on
    entity_id: scene.night
