- alias: Patio - Motion On
  trigger:
    platform: state
    entity_id: binary_sensor.patio_motion
    to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: switch.turn_on
      entity_id: switch.patio
    - service: timer.start
      entity_id: timer.patio_lights_off

- alias: Patio - Off after 10
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.patio_lights_off
  action:
    - service: switch.turn_off
      entity_id: switch.patio

- alias: Patio - Door sensor on
  trigger:
    platform: state
    entity_id: binary_sensor.backdoor_sensor
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: switch.turn_on
      entity_id: switch.patio
    - service: timer.start
      entity_id: timer.patio_lights_off

- alias: Pico - On
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.main_pico
    to: '1'
  action:
    service: scene.turn_on
    entity_id: scene.daytime

- alias: Pico - Off
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.main_pico
    to: '4'
  action:
    service: scene.turn_on
    entity_id: scene.mains_off

- alias: Pico - Up
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.main_pico
    to: '8'
  action:
    service: scene.turn_on
    entity_id: scene.evening

- alias: Pico - Down
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.main_pico
    to: '16'
  action:
    service: scene.turn_on
    entity_id: scene.night

- alias: Pico - Button
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.main_pico
    to: '2'
  action:
    service: light.turn_off
    entity_id: group.all_lights

- alias: Lights on before sunset
  hide_entity: True
  trigger:
    platform: sun
    event: sunset
    offset: '-02:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.daytime

- alias: Front porch lights on at sunset
  hide_entity: True
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    entity_id: light.front_porch_overhead_light

- alias: Front porch lights off at sunrise
  hide_entity: True
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id: light.front_porch_overhead_light

- alias: Evening lighting at 9:00
  hide_entity: True
  trigger:
    platform: time
    at: '21:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.evening

- alias: Mains off in morning
  hide_entity: True
  trigger:
    platform: sun
    event: sunrise
    offset: '01:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.mains_off

- alias: Ignore motion after mains off
  hide_entity: True
  trigger:
    platform: state
    entity_id: light.main_lights
    to: 'off'
  action:
    service: timer.start
    entity_id: timer.livingroom_motion_ignore

- alias: Mains on night Motion
  trigger:
    platform: state
    entity_id: binary_sensor.livingroom
    to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: time
          after: '21:30:00'
        - condition: sun
          before: sunrise
          before_offset: '01:00:00'
    - condition: state
      entity_id: counter.livingroom_motion_ignore
      state: 'idle'
  action:
    service: scene.turn_on
    entity_id: scene.night
