- alias: Patio - Motion On
  trigger:
    platform: state
    entity_id: binary_sensor.patio_motion
    to: 'on'
  condition:
    - condition: state
      entity_id: switch.patio
      state: 'off'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: switch.turn_on
      entity_id: switch.patio
    - service: counter.increment
      entity_id: counter.patio_motion_trigger

- alias: Patio - Motion Off
  trigger:
    platform: state
    entity_id: binary_sensor.patio_motion
    to: 'off'
    for:
      minutes: 10
  condition:
    - condition: numeric_state
      entity_id: counter.patio_motion_trigger
      above: 0
  action:
    - service: switch.turn_off
      entity_id: switch.patio
    - service: counter.reset
      entity_id: counter.patio_motion_trigger
