- alias: Patio - Motion On
  trigger:
    platform: state
    entity_id: binary_sensor.patio_motion
    to: 'on'
  condition:
    - condition: state
      entity_id: switch.patio
      state: 'off'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: switch.turn_on
      entity_id: switch.patio
    - service: counter.increment
      entity_id: counter.patio_motion_trigger

- alias: Patio - Motion Off
  trigger:
    platform: state
    entity_id: binary_sensor.patio_motion
    to: 'off'
    for:
      minutes: 10
  condition:
    - condition: numeric_state
      entity_id: counter.patio_motion_trigger
      above: 0
  action:
    - service: switch.turn_off
      entity_id: switch.patio
    - service: counter.reset
      entity_id: counter.patio_motion_trigger

- alias: Living Room - Motion
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: binary_sensor.livingroom
    to: 'on'
  action:
    - service: counter.increment
      entity_id: counter.livingroom_motion_trigger

- alias: Pico to light
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.living_room_pico

- alias: Living Room - Motion Bedtime
  hide_entity: True
  trigger:
    platform: state
    entity_id: counter.livingroom_motion_trigger
  condition:
    - condition: numeric_state
      entity_id: counter.livingroom_motion_trigger
      above: 0
      below: 2
  action:
    - service: scene.turn_on
      entity_id: scene.bedtime

- alias: Living Room - No motion Nightlight
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: binary_sensor.livingroom
    to: 'off'
    for:
      minutes: 10
  action:
    - service: scene.turn_on
      entity_id: scene.nightlight
    - service: counter.reset
      entity_id: counter.livingroom_motion_trigger

- alias: Pico - On
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.living_room_pico
    to: '1'
  action:
    service: scene.turn_on
    entity_id: scene.living

- alias: Pico - Off
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.living_room_pico
    to: '4'
  action:
    service: light.turn_off
    entity_id: group.all_lights

- alias: Pico - Up
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.living_room_pico
    to: '8'
  action:
    service: scene.turn_on
    entity_id: scene.bedtime

- alias: Pico - Down
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.living_room_pico
    to: '16'
  action:
    service: scene.turn_on
    entity_id: scene.nightlight

- alias: Pico - Button
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.living_room_pico
    to: '2'
  action:
    service: scene.turn_on
    entity_id: scene.lamp
