- alias: Turn on patio light when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.patio_motion
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.patio

- alias: Turn off patio light 10 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.patio_motion
    to: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.patio
