homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 45.561786
  longitude: -122.631477
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 500

lutron_caseta_pro:
  bridges:
    - host: 192.168.86.73

light:
  - platform: group
    name: Main lights
    entities:
      - light.living_room
      - light.dining_room
      - light.dining_room_chandelier

pico_dimmer:
  - sensor: sensor.basement_game_area_pico
    light: light.game
  - sensor: sensor.master_bedroom_pico
    light: light.bedroom

logger:
  default: error
  logs:
    custom_components.pico_dimmer: debug

counter:
  patio_motion_trigger:
    initial: 0
    step: 1

timer:
  patio_lights_off:
    duration: '00:07:00'
  livingroom_motion_ignore:
    duration: '00:00:30'

media_player:
  - platform: denonavr
  - platform: webostv
    host: 192.168.86.77
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: 38:8C:50:B4:4A:47

hue:
  bridges:
    - host: 192.168.86.26

ios:

# Enables the frontend
frontend:

# Enables configuration UI
config:

wake_on_lan:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: 5314.duckdns.org:8123
  ssl_certificate: /home/homeassistant/dehydrated/certs/5314.duckdns.org/fullchain.pem
  ssl_key: /home/homeassistant/dehydrated/certs/5314.duckdns.org/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
    name: Weather

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

scene:
  - name: Evening
    entities:
      light.lamp:
        state: on
        brightness: 135
      light.lower_lamp:
        state: on
        brightness: 67
      light.dining_room_chandelier:
        state: on
        brightness: 90
      light.dining_room:
        state: on
        brightness: 90
      light.bathroom_vanity:
        state: on
        brightness: 90
      light.nursery:
        state: on
        brightness: 90
  - name: Night
    entities:
      light.lamp:
        state: on
        brightness: 2
      light.lower_lamp:
        state: on
        brightness: 1
      light.dining_room_chandelier:
        state: on
        brightness: 60
      light.dining_room:
        state: on
        brightness: 45
      light.bathroom_vanity:
        state: on
        brightness: 45
      light.nursery:
        state: on
        brightness: 30
  - name: Daytime
    entities:
      light.lamp:
        state: on
        brightness: 254
      light.lower_lamp:
        state: on
        brightness: 125
      light.dining_room_chandelier:
        state: on
        brightness: 160
      light.dining_room:
        state: on
        brightness: 115
      light.nursery:
        state: on
        brightness: 115
  - name: Mains off
    entities:
      light.lamp:
        state: off
      light.lower_lamp:
        state: off
      light.dining_room_chandelier:
        state: off
      light.dining_room:
        state: off
      light.bathroom_vanity:
        state: off
      light.nursery:
        state: off

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
